import React from 'react';
import { Link } from 'react-router-dom';
import { LogoMark, ArrowLeftIcon } from '../components/icons';
import { usePageMeta } from '../lib/pageMeta';

export const PrivacyPage: React.FC = () => {
  usePageMeta('Privacy Policy — BrandCore', 'How BrandCore collects, uses, and protects your data.');
  return (
  <div className="min-h-dvh bg-brand-bg">
    <header className="border-b border-brand-border">
      <div className="max-w-3xl mx-auto px-6 h-16 flex items-center justify-between">
        <Link to="/" className="inline-flex items-center gap-2">
          <LogoMark className="w-6 h-6 text-brand-primary" />
          <span className="text-sm font-semibold text-brand-text">BrandCore</span>
        </Link>
        <Link to="/" className="text-sm text-brand-muted hover:text-brand-text inline-flex items-center gap-1.5 transition-colors">
          <ArrowLeftIcon className="w-4 h-4" />
          Back
        </Link>
      </div>
    </header>

    <main className="max-w-3xl mx-auto px-6 py-16">
      <p className="text-xs font-medium uppercase tracking-wide text-brand-muted">Legal</p>
      <h1 className="font-display text-4xl tracking-tighter text-brand-text mt-2">Privacy policy</h1>
      <p className="text-sm text-brand-faint mt-2">Last updated August 2026</p>

      <div className="prose-sm mt-10 space-y-8 text-sm text-brand-text/85 leading-relaxed max-w-[65ch]">
        <section>
          <h2 className="font-semibold text-brand-text text-base mb-2">What we store</h2>
          <p>
            Your account email and a salted, hashed password (Argon2 - we never store or see your
            plaintext password). When you scan a website, we store the crawled page content, extracted
            colors, typography, and tone signals against your workspace, along with any campaigns you
            generate from that profile.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-text text-base mb-2">Usage and cost tracking</h2>
          <p>
            We record token and cost usage per request so we can enforce tier limits and show you
            accurate usage. This is operational telemetry (via OpenTelemetry spans), not used for
            advertising or sold to third parties.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-text text-base mb-2">Third-party processing</h2>
          <p>
            Campaign copy, brand analysis, campaign ideas, and text-based Brand QA review are
            generated by sending your prompt and brand profile to Groq&rsquo;s API (running
            open-weight models). Generated images are reviewed for brand-fit by sending them to
            Google&rsquo;s Gemini API, which also generates embeddings for website knowledge search.
            Generated images themselves use the Pollinations/FLUX image service. Website crawling
            happens server-side and respects each target site&rsquo;s robots.txt.
          </p>
        </section>

        <section>
          <h2 className="font-semibold text-brand-text text-base mb-2">Deleting your data</h2>
          <p>
            Signing out revokes your active session token. To request full account and data deletion,
            contact <a href="mailto:support@brandcore.app" className="text-brand-primary hover:underline">support@brandcore.app</a>.
          </p>
        </section>
      </div>
    </main>
  </div>
  );
};
